### ISSUE TITLE
Update Python to 2021.26

### ISSUE THREAD

**Issue by avaneev** [avaneev/biteopt#2]
@leonidk Could you please update your Python package to the latest BiteOpt version 2021.26

**Comment by leonidk** [comment]
i should have done it. I don't have access to my windows and linux machines right now to check that it works on all platforms still, but it should be synced. 

hopefully will have time this weekend. but the current github + pypi versions should be current with today's master for 0.2.3

**Comment by avaneev** [comment]
Thank you!
