### ISSUE TITLE
New python wrapper with scipy.optimize style API available

### ISSUE THREAD

**Issue by dschmitz89** [avaneev/biteopt#4]
Hey everyone,

I just released a second python wrapper building upon the [existing one](https://github.com/leonidk/biteopt) which mimcs scipy.optimize: https://scipybiteopt.readthedocs.io/en/latest/index.html

Apart from the scipy.optimize API many pythonistas are familiar with this wrapper also offers:

* support for objective functions which take numpy arrays as optimization parameter
* support for additional arguments in the objective 

Suggestions or help are welcome :)

**Comment by avaneev** [comment]
Hello! Thanks! The biteopt project page, however, does not have that much traffic to ask for comments. :-)

**Comment by avaneev** [comment]
FYI, I've added a link to your Python wrapper on project's frontpage.

**Comment by avaneev** [comment]
@dschmitz89 Biteopt actually has built-in convergence check. Simply stop solving when optimize() returns value > 64*Dims.

**Comment by avaneev** [comment]
You could add a Python parameter for this convergence check.

**Comment by avaneev** [comment]
@dschmitz89 I would implement it as a "stopping criteria" with values 0, 1 and 2. 0 being "off", 1 being "64*Dims", 2 being "128*Dims".

**Comment by dschmitz89** [comment]
Good point, will try to implement it, will make the wrapper a lot better . Not sure I totally understand still: Which parameter must be checked? Do not find it in the comment. function signature is 

`biteopt_minimize( const int N, biteopt_func f, void* data,
	const double* lb, const double* ub, double* x, double* minf,
	const int iter, const int M = 1, const int attc = 10 )`

**Comment by avaneev** [comment]
I've updated biteopt_minimize() - you can check it out. Also example2.cpp now reflects this use case.

**Comment by avaneev** [comment]
Now you may also obtain the number of function evaluations performed as biteopt_minimize() return value.

**Comment by dschmitz89** [comment]
Thanks. Can get it done until end of the year.

One last question for me and other users: what is the convergence criterion mathematically?

**Comment by avaneev** [comment]
Well, in case of Biteopt it's the number of non-improving iterations. For derivative-free methods it's the only reliable criterion, because method does not know anything about the problem being solved. I think derivative-based methods evaluate "plateau" or zero derivative to stop the search.

**Comment by dschmitz89** [comment]
Yep, had expected such a criterion. Just to make it 100% clear also for the docstring: to evaluate that the solution does not change anymore, do you use the differences between the objective values of the different populations?

**Comment by avaneev** [comment]
No, differences between objective values are not evaluated. Only the fact whether or not new better solutions are found is used. When a new solution is not found in a round, it's called a "stall". So, 64\*Dims with Dims=10 means that after 640 "stalls" the search is finished.

**Comment by avaneev** [comment]
This is a well-tested method, by the way.

**Comment by dschmitz89** [comment]
I am very much convinced that the method works. Just wanted it to make more transparent to users. Other optimization packages include detailes criteria such as tolerances for detecting the plateau as you mentioned etc. Will let you know here when the Python wrapper is updated.

**Comment by avaneev** [comment]
Thanks. Both "stopc=1" and "stopc=2" still find optimum in 96-98% of problems, but allow the user to specify large iteration budgets, and not worry about actual solution time.

**Comment by dschmitz89** [comment]
Python package is updated. Decided to give user the option of tol="hard","low",None to make it a bit more pythonic.
Thanks again!
