### ISSUE TITLE
Additional stopping criterion: objective function value

### ISSUE THREAD

**Issue by dschmitz89** [avaneev/biteopt#5]
Hey there,

for benchmarking purposes it would be very helpful if biteopt could be stopped when it reaches a given objective function value. This is also done in nlopt for example. Would you be open to implement this in biteopt?

As another example: For a recent addition to scipy ([DIRECT](https://output.circle-artifacts.com/output/job/9f5b6d74-8b35-43f6-9630-10f462b99c67/artifacts/0/html/reference/generated/scipy.optimize.direct.html#scipy.optimize.direct)), we chose to have two keywords: `f_min` and `f_min_rtol`, the desired relative tolerance within `f_min`.

**Comment by avaneev** [comment]
I've added the `f_min` parameter to biteopt_minimize(). Careful with parameter order as the function now has a lot of parameters. I think `f_min_rtol` can be converted to `f_min` by the caller as benchmarks usually use their own approach. Some just add a constant, others use percentage. Also, zero `f_min` values are often handled differently: I prefer equate zero to 1e-6, others prefer fullscale 1e-15.

**Comment by avaneev** [comment]
Also note that `stopc` is now preferrable to be multiplied by 128, and not 64. In many complex problems, 1\*64\*dims stops too early, for example. Some combinatorial problems give good results while still offering a performance advantage with stopc as large as 20 or 30.

**Comment by dschmitz89** [comment]
Thanks!

**Comment by dschmitz89** [comment]
Last minor think: I think the README needs an update too. The API description does not contain the new parameter.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/40656107/173445990-62944dfb-0f04-441f-ae9d-ee111e3b6f65.png">

**Comment by avaneev** [comment]
@dschmitz89 Hi! Have you had time to compare DIRECT to BiteOpt? Which one wins in SciPy?

**Comment by dschmitz89** [comment]
Biteopt is clear winner solved 179 out of 194 benchmark problems of scipy's test suite with an outdated biteopt version.

Properly wrapping biteopt in scipy is still an open topic

**Comment by avaneev** [comment]
Thanks. Note that "fmin" is a *pointer*, so your worry does not apply.

**Comment by avaneev** [comment]
@dschmitz89 Please help me resolve my "Seasickness". You (and others) admit Biteopt is winner, yet no hurry to include it into Scipy to help many scientists to solve practical problems. I just want to understand, maybe there's some psychological or even political culprit exists.

By the way, I plan to implement "out of the box" multi-threaded biteopt_minimize in case Biteopt is included into Scipy... At the moment there's no motivation.

**Comment by avaneev** [comment]
Hi! How this progresses, if at all? By the way, how DIRECT fares against latest BiteOpt, in the framework of Scipy optimization benchmark?
