### ISSUE TITLE
wrapParamReal gives parameters outside of range; a typo?

### ISSUE THREAD

**Issue by tom7** [avaneev/biteopt#6]
In `wrapParamReal`, is the line

```
return( maxv - rnd.get() * ( v - dv ));
```

supposed to be 

```
return( maxv - rnd.get() * ( v - maxv ));
```

? This would mirror the symmetric case for when `v` < `minv`. In any case, the current code can return a parameter value outside the range. In my test case I have `minv`: -1000, `maxv`: 1000, so `dv` = 2000. The incoming sample is 1039.54, which reaches [line 1802](https://github.com/avaneev/biteopt/blob/56bcb7939f155909a5d5b747dd3f08ee403fc611/biteaux.h#L1802), giving `1000 - rnd.get() * (1039.54 - 2000)`. Since `rnd.get()` is in [0,1] and the parenthetical is negative, we get a resulting sample greater than 1000, the supposed maximum.

Thanks for biteopt! :)

**Comment by avaneev** [comment]
Thank you for reporting the bug, I've just re-run all tests and released an update - should be okay now in this aspect.

Note that this bug mainly affected NMSOpt which is a sub-optimizer. BiteOpt itself is based on wrapParam() which works correctly.

**Comment by avaneev** [comment]
Sorry for a bit unrelated comment, by I think that "anger induction" is effective until target has "anger logic" that can be excited. Practically, mind strives to be in equilibrium thus "anger logic" in society may become extinct over time, if abused.
